OVAL in foreman_openscap
theforeman/foreman_openscap pull request #458
Opened 2020-11-18 14:25 UTC by xprazak2

Contains #456 and #457 on top of each other for easier testing.

It should be possible to create oval policy with oval content and assign it to host(group)s.

OVAL content from RH stream is bzipped, I managed to upload with:

```
echo "{ \"oval_content\": { \"scap_file\": \"$(base64 -w 0 ~/Downloads/whatever.oval.xml.bz2)\"  } }" | curl -H "Accept: application/json" -H "Content-Type: application/json" -k -X PUT -u admin:changeme https://centos-devel.example.com/api/v2/compliance/oval_contents/3 -d @-  | json_reformat
``` 

though we might need to think about whether we want to unzip before uploading.

2020-11-24 12:17 UTC, xprazak2 commented
Foreman is now able to attach CVEs to hosts and set OVAL status.

2020-12-17 16:13 UTC, xprazak2 commented
I added changes to keep track of CVEs without Errata, I also updated the report template on foreman side.

2021-04-06 08:19 UTC, xprazak2 commented
[test foreman_openscap]

2021-04-22 13:55 UTC, ares requested changes
I have tested the functionality end to end and it works pretty well! Leaving a few smaller comments here.

2021-04-22 13:55 UTC, ares commented on app/models/foreman_openscap/oval_status.rb
> +    VULNERABLE = 1
Ideally we'd have 3 different states

OK - no CVEs found (0 CVEs records for the host)
Warning - CVEs found, no errata available for any of them
Error - CVEs found, errata for them exist (patch available, but not applied)

2021-04-23 11:35 UTC, xprazak2 commented on app/models/foreman_openscap/oval_status.rb
> +    end
If there is at least one CVE with existing errata, status will be error.

2021-04-28 08:33 UTC, ares commented
[test foreman_openscap], code looks good now, I'm retesting the functionality, failures seemed unrelated

2021-04-28 09:07 UTC, ares requested changes
I found that parsing the report creates SQL per each CVE. We don't have to address it here, but some performance tweaking will be necessary. Here's the sample of the SQL log.

```
2021-04-28T10:53:26 [D|sql|e4b3d4a0]   ↳ /home/ares/Projekty/Zdrojaky/foreman_openscap/app/services/foreman_openscap/oval/cves.rb:10:in `block (2 levels) in create'
2021-04-28T10:53:26 [D|sql|e4b3d4a0]   ForemanOpenscap::Cve Load (0.9ms)  SELECT "foreman_openscap_cves".* FROM "foreman_openscap_cves" WHERE "foreman_openscap_cves"."ref_id" = $1 AND "foreman_openscap_cves"."ref_url" = $2 AND "foreman_openscap_cves"."has_errata" = $3 AND "foreman_openscap_cves"."definition_id" = $4 LIMIT $5  [["ref_id", "CVE-2014-3537"], ["ref_url", "https://access.redhat.com/security/cve/CVE-2014-3537"], ["has_errata", true], ["definition_id", "oval:com.redhat.rhba:def:20150386"], ["LIMIT", 1]]
2021-04-28T10:53:26 [D|sql|e4b3d4a0]   ↳ /home/ares/Projekty/Zdrojaky/foreman_openscap/app/services/foreman_openscap/oval/cves.rb:10:in `block (2 levels) in create'
2021-04-28T10:53:26 [D|sql|e4b3d4a0]   ForemanOpenscap::Cve Load (1.0ms)  SELECT "foreman_openscap_cves".* FROM "foreman_openscap_cves" WHERE "foreman_openscap_cves"."ref_id" = $1 AND "foreman_openscap_cves"."ref_url" = $2 AND "foreman_openscap_cves"."has_errata" = $3 AND "foreman_openscap_cves"."definition_id" = $4 LIMIT $5  [["ref_id", "CVE-2014-5029"], ["ref_url", "https://access.redhat.com/security/cve/CVE-2014-5029"], ["has_errata", true], ["definition_id", "oval:com.redhat.rhba:def:20150386"], ["LIMIT", 1]]
2021-04-28T10:53:26 [D|sql|e4b3d4a0]   ↳ /home/ares/Projekty/Zdrojaky/foreman_openscap/app/services/foreman_openscap/oval/cves.rb:10:in `block (2 levels) in create'
2021-04-28T10:53:26 [D|sql|e4b3d4a0]   ForemanOpenscap::Cve Load (0.9ms)  SELECT "foreman_openscap_cves".* FROM "foreman_openscap_cves" WHERE "foreman_openscap_cves"."ref_id" = $1 AND "foreman_openscap_cves"."ref_url" = $2 AND "foreman_openscap_cves"."has_errata" = $3 AND "foreman_openscap_cves"."definition_id" = $4 LIMIT $5  [["ref_id", "CVE-2014-5030"], ["ref_url", "https://access.redhat.com/security/cve/CVE-2014-5030"], ["has_errata", true], ["definition_id", "oval:com.redhat.rhba:def:20150386"], ["LIMIT", 1]]
2021-04-28T10:53:26 [D|sql|e4b3d4a0]   ↳ /home/ares/Projekty/Zdrojaky/foreman_openscap/app/services/foreman_openscap/oval/cves.rb:10:in `block (2 levels) in create'
2021-04-28T10:53:26 [D|sql|e4b3d4a0]   ForemanOpenscap::Cve Load (0.9ms)  SELECT "foreman_openscap_cves".* FROM "foreman_openscap_cves" WHERE "foreman_openscap_cves"."ref_id" = $1 AND "foreman_openscap_cves"."ref_url" = $2 AND "foreman_openscap_cves"."has_errata" = $3 AND "foreman_openscap_cves"."definition_id" = $4 LIMIT $5  [["ref_id", "CVE-2014-5031"], ["ref_url", "https://access.redhat.com/security/cve/CVE-2014-5031"], ["has_errata", true], ["definition_id", "oval:com.redhat.rhba:def:20150386"], ["LIMIT", 1]]
2021-04-28T10:53:26 [D|sql|e4b3d4a0]   ↳ /home/ares/Projekty/Zdrojaky/foreman_openscap/app/services/foreman_openscap/oval/cves.rb:10:in `block (2 levels) in create'
2021-04-28T10:53:26 [D|sql|e4b3d4a0]   ForemanOpenscap::Cve Load (0.9ms)  SELECT "foreman_openscap_cves".* FROM "foreman_openscap_cves" WHERE "foreman_openscap_cves"."ref_id" = $1 AND "foreman_openscap_cves"."ref_url" = $2 AND "foreman_openscap_cves"."has_errata" = $3 AND "foreman_openscap_cves"."definition_id" = $4 LIMIT $5  [["ref_id", "CVE-2014-1545"], ["ref_url", "https://access.redhat.com/security/cve/CVE-2014-1545"], ["has_errata", true], ["definition_id", "oval:com.redhat.rhba:def:20150364"], ["LIMIT", 1]]
2021-04-28T10:53:26 [D|sql|e4b3d4a0]   ↳ /home/ares/Projekty/Zdrojaky/foreman_openscap/app/services/foreman_openscap/oval/cves.rb:10:in `block (2 levels) in create'
2021-04-28T10:53:26 [D|sql|e4b3d4a0]    (3.8ms)  SELECT "foreman_openscap_cves"."id" FROM "foreman_openscap_cves" INNER JOIN "foreman_openscap_host_cves" ON "foreman_openscap_cves"."id" = "foreman_openscap_host_cves"."cve_id" WHERE "foreman_openscap_host_cves"."host_id" = $1  [["host_id", 76]]
```

Also it creates instance of `HostStatus::Status` instead of `ForemanOpenscap::OvalStatus` which then fails to display. That's the last thing that needs fixing (added a comment in the code)

2021-04-28 09:07 UTC, ares commented on app/controllers/api/v2/compliance/oval_reports_controller.rb
> +            @host.refresh_statuses([HostStatus.find_status_by_humanized_name("oval")])
`@host.refresh_statuses([HostStatus.find_status_by_humanized_name("oval")])` this no longer works, it should be
`@host.refresh_statuses([ForemanOpenscap::OvalStatus])`

2021-04-28 09:30 UTC, xprazak2 commented
I updated the status refresh, I'll tweak the performance separately. Some tests from core will not pass due to interaction with rex, that is why I opened the PR to move to gh actions for testing (which can be done later).

2021-04-28 10:56 UTC, ares approved these changes
Ack pending tests not showing anything new, will merge right after.

2021-04-28 12:37 UTC, ares approved these changes
Thanks @xprazak2, merging!

2021-04-28 12:38 UTC, merged