Fixes #38006 - Allow extension of list of packages
theforeman/foreman_openscap pull request #585
Opened 2024-11-12 12:08 UTC by adamruzicka

with scap contents

2024-11-12 12:49 UTC, evgeni commented on lib/foreman_openscap/bulk_upload.rb
> +        @result.errors.push(_("Can't find #{security_guide_packages.join(' or ')} RPM(s), are you sure it is installed on your server?"))
The join should happen outside the translated string

2024-11-29 16:56 UTC, ofedoren reviewed
Thanks, @adamruzicka, LGTM.

I've got only two comments:
 - Just a note: it kinda seems that there more changes than needed if we only care if any of these packages are installed. If we expect this list to be updated from even other plugins and the name of the package can differ from `scap-security-guide`, then it's fine. Or, if `theme_satellite` must enforce that `scap-sec-g-satellite` must have preference over the default one.
 - Requirement? :) I've tested with the counterpart, but it failed to load. It seems `BulkUpload` constant is not available during `foreman_theme_satellite` registration in `engine.rb`. That is probably I test on Rails 7 though. Long story short, could we move `bulk_upload.rb` into either `app/lib/foreman_openscap` or `app/services/foreman_openscap`? And just for complicity, remove https://github.com/theforeman/foreman_openscap/blob/master/app/controllers/api/v2/compliance/scap_contents_controller.rb#L1 and https://github.com/theforeman/foreman_openscap/blob/master/test/lib/foreman_openscap/bulk_upload_test.rb#L5 and https://github.com/theforeman/foreman_openscap/blob/master/lib/tasks/foreman_openscap_tasks.rake#L3

2024-12-02 10:20 UTC, adamruzicka commented
> If we expect this list to be updated from even other plugins

I don't really see that happening.

> Or, if theme_satellite must enforce that scap-sec-g-satellite must have preference over the default one.

Yeah, it must :/

> Requirement?

I'll take a look

2024-12-02 16:20 UTC, ofedoren requested changes
Thanks, @adamruzicka, and please don't hate me, just a small nitpick. Otherwise, LGTM and seems to be working.

2024-12-03 12:47 UTC, ofedoren approved these changes
Thanks, @adamruzicka !

2024-12-03 12:47 UTC, merged